# Generated by Django 5.0.6 on 2024-06-12 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255, unique=True)),
                ('company_address', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
            ],
        ),
    ]
