# Generated by Django 5.0.6 on 2024-06-13 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=155)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('tech_id', models.ManyToManyField(to='Client.technology')),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.team')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
